CREATE DATABASE [GBUMATC]
GO

ALTER DATABASE [GBUMATC]
  SET
    ANSI_NULL_DEFAULT OFF,
    ANSI_NULLS ON,
    ANSI_PADDING OFF,
    ANSI_WARNINGS OFF,
    ARITHABORT OFF,
    AUTO_CLOSE OFF,
    AUTO_CREATE_STATISTICS ON,
    AUTO_SHRINK ON,
    AUTO_UPDATE_STATISTICS ON,
    AUTO_UPDATE_STATISTICS_ASYNC OFF,
    COMPATIBILITY_LEVEL = 120,
    CONCAT_NULL_YIELDS_NULL OFF,
    CURSOR_CLOSE_ON_COMMIT ON,
    CURSOR_DEFAULT GLOBAL,
    DATE_CORRELATION_OPTIMIZATION OFF,
    DB_CHAINING OFF,
    HONOR_BROKER_PRIORITY OFF,
    MULTI_USER,
    NESTED_TRIGGERS = ON,
    NUMERIC_ROUNDABORT OFF,
    PAGE_VERIFY CHECKSUM,
    PARAMETERIZATION SIMPLE,
    QUOTED_IDENTIFIER OFF,
    READ_COMMITTED_SNAPSHOT OFF,
    RECOVERY FULL,
    RECURSIVE_TRIGGERS OFF,
    TRANSFORM_NOISE_WORDS = OFF,
    TRUSTWORTHY OFF
    WITH ROLLBACK IMMEDIATE
GO

ALTER DATABASE [GBUMATC]
  COLLATE Cyrillic_General_CI_AS
GO

ALTER DATABASE [GBUMATC]
  SET DISABLE_BROKER
GO

ALTER DATABASE [GBUMATC]
  SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [GBUMATC]
  SET FILESTREAM (NON_TRANSACTED_ACCESS = FULL, DIRECTORY_NAME = 'GBUMATCFileStream')
GO

ALTER DATABASE [GBUMATC]
  SET CHANGE_TRACKING = ON
GO

ALTER AUTHORIZATION ON DATABASE :: [GBUMATC] TO [Бушмакин]
GO

EXEC sys.sp_addextendedproperty N'HasClusteredColumnStoreIndex', N'1'
GO

GRANT CONNECT TO [base]
GO

GRANT CONNECT TO [Bushmakin]
GO

GRANT CONNECT TO [Bushmakin1]
GO

GRANT CONNECT TO [dbase]
GO

GRANT CONNECT TO [dbo]
GO

GRANT
  CONNECT,
  INSERT,
  SELECT,
  UPDATE TO [IIS APPPool\db2015]
GO

GRANT
  CONNECT,
  INSERT,
  SELECT,
  UPDATE TO [IIS APPPool\sp2]
GO

GRANT
  CONNECT,
  INSERT,
  SELECT,
  UPDATE TO [IIS APPPool\tbo]
GO

GRANT CONNECT TO [iisuser]
GO

GRANT CONNECT TO [maksimov]
GO

GRANT CONNECT TO [NT AUTHORITY\IUSR]
GO

GRANT CONNECT TO [NT AUTHORITY\LOCAL SERVICE]
GO

GRANT CONNECT TO [NT AUTHORITY\NETWORK SERVICE]
GO

GRANT CONNECT TO [NT AUTHORITY\Локальная учетная запись]
GO

GRANT CONNECT TO [NT AUTHORITY\СЕТЬ]
GO

GRANT CONNECT TO [NT AUTHORITY\система]
GO

GRANT CONNECT TO [NT AUTHORITY\СЛУЖБА]
GO

GRANT CONNECT TO [user]
GO

GRANT CONNECT TO [Амосова Е.В.]
GO

GRANT CONNECT TO [Бороздин В.А.]
GO

GRANT CONNECT TO [Борский И.В.]
GO

GRANT CONNECT TO [Бушмакин]
GO

GRANT CONNECT TO [Быков Е.М.]
GO

GRANT CONNECT TO [Волкова Е.А.]
GO

GRANT CONNECT TO [Галиев В.И.]
GO

GRANT CONNECT TO [Гость]
GO

GRANT CONNECT TO [Григорьев Я.А.]
GO

GRANT CONNECT TO [Дубинин А.А.]
GO

GRANT CONNECT TO [Жаренова Е.И.]
GO

GRANT CONNECT TO [Иваницын М.А.]
GO

GRANT CONNECT TO [Игнатов А.М.]
GO

GRANT CONNECT TO [Исаева Е.Н.]
GO

GRANT CONNECT TO [Кильдишев А.С.]
GO

GRANT CONNECT TO [Ковалев А.В]
GO

GRANT CONNECT TO [Колбунцова М.В.]
GO

GRANT CONNECT TO [Крылова Г.В.]
GO

GRANT CONNECT TO [Кряков Л.Н.]
GO

GRANT CONNECT TO [Курцева И.С.]
GO

GRANT CONNECT TO [Ладунский А.И.]
GO

GRANT CONNECT TO [Ломаева Н.Г.]
GO

GRANT CONNECT TO [Лукин В.В.]
GO

GRANT CONNECT TO [Максимов С.В.]
GO

GRANT CONNECT TO [Малых А.В.]
GO

GRANT CONNECT TO [Мамедов К.Ю.]
GO

GRANT CONNECT TO [Мешалкин А.А.]
GO

GRANT CONNECT TO [Митителу П.Д.]
GO

GRANT CONNECT TO [Мураховская Е.С.]
GO

GRANT CONNECT TO [Мышев А.Б.]
GO

GRANT CONNECT TO [Ней К.Н.]
GO

GRANT CONNECT TO [Оборская Н.Е.]
GO

GRANT
  ALTER,
  CONNECT,
  EXECUTE,
  SELECT TO [Перевощиков С.А.]
GO

GRANT CONNECT TO [Петрусенко Н.А.]
GO

GRANT CONNECT TO [Понин Я.И.]
GO

GRANT CONNECT TO [Потаева В.В.]
GO

GRANT CONNECT TO [Русак И.Б.]
GO

GRANT CONNECT TO [Рыжкова Т.Ф.]
GO

GRANT CONNECT TO [Савин К.М.]
GO

GRANT CONNECT TO [Савчук В.С.]
GO

GRANT CONNECT TO [Солодюк Е.И.]
GO

GRANT CONNECT TO [Сорокина Ю.А.]
GO

GRANT CONNECT TO [Сотников С.А.]
GO

GRANT CONNECT TO [Степаненко И.В.]
GO

GRANT CONNECT TO [Счастливцева С.А.]
GO

GRANT CONNECT TO [Тимофеев Д.А.]
GO

GRANT CONNECT TO [Усков П.Ю.]
GO

GRANT CONNECT TO [Федосеева Л.Е.]
GO

GRANT CONNECT TO [Хохлов Д.С.]
GO

GRANT CONNECT TO [Хусаинова Е.Т.]
GO

GRANT CONNECT TO [Цветков А.Ю.]
GO

GRANT CONNECT TO [Чернов И.В.]
GO

GRANT CONNECT TO [Щербинина М.В.]
GO

GRANT CONNECT TO [Яблочник Е.А.]
GO

GRANT CONNECT TO [Ямин Я.Ю.]
GO