CREATE TABLE [dbo].[ТехсостояниеГУ] (
  [Уникальный номер информационного указателя] [nvarchar](255) NULL,
  [Округ] [nvarchar](255) NULL,
  [Нас# Пункт] [nvarchar](255) NULL,
  [Район] [nvarchar](255) NULL,
  [Улица, проспект, пер# и проч] [nvarchar](255) NULL,
  [Дом, корп#, стр# и проч] [nvarchar](255) NULL,
  [Ответственный] [nvarchar](255) NULL,
  [Проверено] [datetime] NULL,
  [Установлен] [nvarchar](255) NULL,
  [Аварийная конструкция] [nvarchar](255) NULL,
  [Механическое повреждение опоры] [nvarchar](255) NULL,
  [Сломаны информационные поля] [nvarchar](255) NULL,
  [Повреждены информационные поля] [nvarchar](255) NULL,
  [Сломаны направляющие информационных полей] [nvarchar](255) NULL,
  [Повреждены направляющие информационных полей] [nvarchar](255) NULL,
  [Поврежден декоративный колпак] [nvarchar](255) NULL,
  [Разбит декоративный колпак] [nvarchar](255) NULL,
  [Поврежден инфокуб] [nvarchar](255) NULL,
  [Отсутствует инфокуб] [nvarchar](255) NULL,
  [Наличие ржавчины на опоре] [nvarchar](255) NULL,
  [Отслоение краски с опоры] [nvarchar](255) NULL,
  [Отслоение краски с направляющих информационных полей] [nvarchar](255) NULL,
  [Конструкция испачкана краской] [nvarchar](255) NULL,
  [Конструкция оклеена объявлениями] [nvarchar](255) NULL,
  [Загрязнение конструкции] [nvarchar](255) NULL,
  [Отсутствуют заглушки отверстий в опоре] [nvarchar](255) NULL,
  [Не благоустроена территория] [nvarchar](255) NULL,
  [Отсутствуют реквизиты] [float] NULL,
  [Неправильные реквизиты] [nvarchar](255) NULL,
  [С замечаниями] [nvarchar](255) NULL,
  [Проверка] [nvarchar](255) NULL,
  [Документ] [nvarchar](255) NULL,
  [F33] [nvarchar](255) NULL,
  [F34] [nvarchar](255) NULL,
  [F35] [nvarchar](255) NULL,
  [F36] [nvarchar](255) NULL,
  [F37] [nvarchar](255) NULL,
  [F38] [nvarchar](255) NULL,
  [F39] [nvarchar](255) NULL,
  [F40] [nvarchar](255) NULL,
  [F41] [nvarchar](255) NULL,
  [F42] [nvarchar](255) NULL,
  [F43] [nvarchar](255) NULL
)
ON [PRIMARY]
GO