SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[mainFileContainer] AS FILETABLE
WITH (
  FILETABLE_COLLATE_FILENAME = Cyrillic_General_CI_AS,
  FILETABLE_PRIMARY_KEY_CONSTRAINT_NAME = [PK__DataBase__5A5B77D5E8E812C6],
  FILETABLE_STREAMID_UNIQUE_CONSTRAINT_NAME = [UQ__DataBase__9DD95BAF738DEAF8],
  FILETABLE_FULLPATH_UNIQUE_CONSTRAINT_NAME = [UQ__DataBase__A236CBB3F6605A3A]
)
GO

GRANT
  ALTER,
  CONTROL,
  DELETE,
  INSERT,
  REFERENCES,
  SELECT,
  TAKE OWNERSHIP,
  UPDATE,
  VIEW CHANGE TRACKING,
  VIEW DEFINITION
ON [dbo].[mainFileContainer] TO [NT AUTHORITY\IUSR]
GO

GRANT
  ALTER,
  CONTROL,
  DELETE,
  INSERT,
  REFERENCES,
  SELECT,
  TAKE OWNERSHIP,
  UPDATE,
  VIEW CHANGE TRACKING,
  VIEW DEFINITION
ON [dbo].[mainFileContainer] TO [NT AUTHORITY\LOCAL SERVICE]
GO

GRANT
  ALTER,
  CONTROL,
  DELETE,
  INSERT,
  REFERENCES,
  SELECT,
  TAKE OWNERSHIP,
  UPDATE,
  VIEW CHANGE TRACKING,
  VIEW DEFINITION
ON [dbo].[mainFileContainer] TO [NT AUTHORITY\NETWORK SERVICE]
GO

GRANT
  ALTER,
  CONTROL,
  DELETE,
  INSERT,
  REFERENCES,
  SELECT,
  TAKE OWNERSHIP,
  UPDATE,
  VIEW CHANGE TRACKING,
  VIEW DEFINITION
ON [dbo].[mainFileContainer] TO [NT AUTHORITY\СЕТЬ]
GO

GRANT
  ALTER,
  CONTROL,
  DELETE,
  INSERT,
  REFERENCES,
  SELECT,
  TAKE OWNERSHIP,
  UPDATE,
  VIEW CHANGE TRACKING,
  VIEW DEFINITION
ON [dbo].[mainFileContainer] TO [NT AUTHORITY\система]
GO

GRANT
  ALTER,
  CONTROL,
  DELETE,
  INSERT,
  REFERENCES,
  SELECT,
  TAKE OWNERSHIP,
  UPDATE,
  VIEW CHANGE TRACKING,
  VIEW DEFINITION
ON [dbo].[mainFileContainer] TO [NT AUTHORITY\СЛУЖБА]
GO