SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Files] AS FILETABLE
WITH (
  FILETABLE_DIRECTORY = 'DataBase',
  FILETABLE_COLLATE_FILENAME = Cyrillic_General_CI_AS,
  FILETABLE_PRIMARY_KEY_CONSTRAINT_NAME = [PK__yyyyyy__5A5B77D5709B3865],
  FILETABLE_STREAMID_UNIQUE_CONSTRAINT_NAME = [UQ__yyyyyy__9DD95BAF492E6119],
  FILETABLE_FULLPATH_UNIQUE_CONSTRAINT_NAME = [UQ__yyyyyy__A236CBB3CCFFE243]
)
GO

GRANT
  ALTER,
  CONTROL,
  DELETE,
  INSERT,
  REFERENCES,
  SELECT,
  TAKE OWNERSHIP,
  UPDATE,
  VIEW CHANGE TRACKING,
  VIEW DEFINITION
ON [dbo].[Files] TO [NT AUTHORITY\СЕТЬ]
GO

GRANT
  ALTER,
  CONTROL,
  DELETE,
  INSERT,
  REFERENCES,
  SELECT,
  TAKE OWNERSHIP,
  UPDATE,
  VIEW CHANGE TRACKING,
  VIEW DEFINITION
ON [dbo].[Files] TO [NT AUTHORITY\система]
GO

GRANT
  ALTER,
  CONTROL,
  DELETE,
  INSERT,
  REFERENCES,
  SELECT,
  TAKE OWNERSHIP,
  UPDATE,
  VIEW CHANGE TRACKING,
  VIEW DEFINITION
ON [dbo].[Files] TO [NT AUTHORITY\СЛУЖБА]
GO

GRANT
  ALTER,
  CONTROL,
  DELETE,
  INSERT,
  REFERENCES,
  SELECT,
  TAKE OWNERSHIP,
  UPDATE,
  VIEW CHANGE TRACKING,
  VIEW DEFINITION
ON [dbo].[Files] TO [Гость]
GO

GRANT
  ALTER,
  CONTROL,
  DELETE,
  INSERT,
  REFERENCES,
  SELECT,
  TAKE OWNERSHIP,
  UPDATE,
  VIEW CHANGE TRACKING,
  VIEW DEFINITION
ON [dbo].[Files] TO [public]
GO