CREATE TABLE [fias].[Object_log] (
  [Object_log_ID] [int] IDENTITY NOT FOR REPLICATION,
  [AOGUID] [uniqueidentifier] NULL,
  [FORMALNAME] [nvarchar](120) NULL,
  [REGIONCODE] [nvarchar](2) NULL,
  [AUTOCODE] [nvarchar](1) NULL,
  [AREACODE] [nvarchar](3) NULL,
  [CITYCODE] [nvarchar](3) NULL,
  [CTARCODE] [nvarchar](3) NULL,
  [PLACECODE] [nvarchar](3) NULL,
  [STREETCODE] [nvarchar](4) NULL,
  [EXTRCODE] [nvarchar](4) NULL,
  [SEXTCODE] [nvarchar](3) NULL,
  [OFFNAME] [nvarchar](120) NULL,
  [POSTALCODE] [nvarchar](6) NULL,
  [IFNSFL] [nvarchar](4) NULL,
  [TERRIFNSFL] [nvarchar](4) NULL,
  [IFNSUL] [nvarchar](4) NULL,
  [TERRIFNSUL] [nvarchar](4) NULL,
  [OKATO] [nvarchar](11) NULL,
  [OKTMO] [nvarchar](11) NULL,
  [UPDATEDATE] [datetime2](3) NULL,
  [SHORTNAME] [nvarchar](10) NULL,
  [AOLEVEL] [int] NULL,
  [PARENTGUID] [uniqueidentifier] NULL,
  [AOID] [uniqueidentifier] NOT NULL,
  [PREVID] [uniqueidentifier] NULL,
  [NEXTID] [uniqueidentifier] NULL,
  [CODE] [nvarchar](17) NULL,
  [PLAINCODE] [nvarchar](15) NULL,
  [ACTSTATUS] [int] NULL,
  [CENTSTATUS] [int] NULL,
  [OPERSTATUS] [int] NULL,
  [CURRSTATUS] [int] NULL,
  [STARTDATE] [datetime2](3) NULL,
  [ENDDATE] [datetime2](3) NULL,
  [NORMDOC] [uniqueidentifier] NULL,
  [LIVESTATUS] [nvarchar](1) NULL,
  [CADNUM] [nvarchar](100) NULL,
  [DIVTYPE] [int] NULL,
  [OFFNAME_NUM_TYPE] [int] NULL,
  [OFFNAME_NUM_NUMBER] [int] NULL,
  [OFFNAME_NUM_PREFIX] [int] NULL,
  [OFFNAME_NUMBER] [varchar](20) NULL,
  [OFFNAME_PREFIX] [varchar](20) NULL,
  [OFFNAME_NAME] [varchar](80) NULL,
  [CONVERTSTREET] [nvarchar](50) NULL,
  [updated] [datetime] NULL DEFAULT (getdate()),
  CONSTRAINT [PK_Key1] PRIMARY KEY CLUSTERED ([Object_log_ID])
)
ON [PRIMARY]
GO